"use client";

import { motion, useInView } from "framer-motion";
import { useRef, useState } from "react";
import { Check, X, HelpCircle, ChevronDown } from "lucide-react";

interface ComparisonRow {
  feature: string;
  googleAdX: { value: string; positive: boolean };
  magnite: { value: string; positive: boolean };
  ours: { value: string; positive: boolean };
  tooltip: string;
}

const comparisonData: ComparisonRow[] = [
  {
    feature: "Middleman Fee",
    googleAdX: { value: "30% - 50%", positive: false },
    magnite: { value: "15% - 25%", positive: false },
    ours: { value: "1% - 5%", positive: true },
    tooltip:
      "Total fees taken from advertiser spend before reaching publishers",
  },
  {
    feature: "Payout Latency",
    googleAdX: { value: "Net-60 (60 days)", positive: false },
    magnite: { value: "Net-30 (30 days)", positive: false },
    ours: { value: "Instant (Real-time)", positive: true },
    tooltip: "Net-60 means publishers wait 60 days to get paid",
  },
  {
    feature: "Auditability",
    googleAdX: { value: 'Closed "Black Box"', positive: false },
    magnite: { value: "Third-party reports", positive: false },
    ours: { value: "On-chain / Immutable", positive: true },
    tooltip: "Ability to verify and audit all transactions and data",
  },
  {
    feature: "Verification",
    googleAdX: { value: "Human-audited", positive: false },
    magnite: { value: "Probabilistic", positive: false },
    ours: { value: "Cryptographic (ZK-Proof)", positive: true },
    tooltip: "Method used to verify ad impressions and prevent fraud",
  },
  {
    feature: "Data Control",
    googleAdX: { value: "Google owns it", positive: false },
    magnite: { value: "Fragmented", positive: false },
    ours: { value: "User-owned / Private", positive: true },
    tooltip: "Who controls and owns the data generated by ad campaigns",
  },
];

export function CompetitiveTable() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });
  const [activeTooltip, setActiveTooltip] = useState<number | null>(null);

  return (
    <section
      id="competitive-landscape"
      className="py-24 lg:py-32 bg-white relative"
    >
      {/* Background decoration */}
      <div className="absolute inset-0 bg-gradient-to-b from-gray-50 to-white" />

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-100 text-indigo-700 text-sm font-medium mb-6">
            Competitive Analysis
          </div>
          <h2
            className="text-4xl md:text-5xl font-bold text-gray-900 mb-6"
            style={{ fontFamily: "Inter, system-ui, sans-serif" }}
          >
            How We Compare
          </h2>
          <p
            className="text-xl text-gray-600 max-w-2xl mx-auto"
            style={{ fontFamily: "Inter, system-ui, sans-serif" }}
          >
            See how our Web3 approach stacks up against traditional ad tech
            giants
          </p>
        </motion.div>

        {/* Desktop Table */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="hidden md:block overflow-hidden rounded-2xl border border-gray-200 shadow-xl bg-white"
        >
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="px-6 py-5 text-left text-sm font-semibold text-gray-900 bg-gray-50 w-1/4">
                  Feature
                </th>
                <th className="px-6 py-5 text-center text-sm font-semibold text-gray-900 bg-gray-50 w-1/4">
                  <div className="flex flex-col items-center gap-1">
                    <span>Google AdX</span>
                    <span className="text-xs font-normal text-gray-500">
                      Industry Leader
                    </span>
                  </div>
                </th>
                <th className="px-6 py-5 text-center text-sm font-semibold text-gray-900 bg-gray-50 w-1/4">
                  <div className="flex flex-col items-center gap-1">
                    <span>Magnite / PubMatic</span>
                    <span className="text-xs font-normal text-gray-500">
                      Major SSPs
                    </span>
                  </div>
                </th>
                <th className="px-6 py-5 text-center text-sm font-semibold bg-emerald-600 text-white w-1/4">
                  <div className="flex flex-col items-center gap-1">
                    <span>Your Startup (Web3)</span>
                    <span className="text-xs font-normal text-emerald-100">
                      The Future
                    </span>
                  </div>
                </th>
              </tr>
            </thead>
            <tbody>
              {comparisonData.map((row, index) => (
                <motion.tr
                  key={row.feature}
                  initial={{ opacity: 0, x: -20 }}
                  animate={isInView ? { opacity: 1, x: 0 } : {}}
                  transition={{ duration: 0.4, delay: 0.3 + index * 0.1 }}
                  className="border-b border-gray-100 hover:bg-gray-50 transition-colors group"
                >
                  <td className="px-6 py-5">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-gray-900">
                        {row.feature}
                      </span>
                      <div className="relative">
                        <button
                          onMouseEnter={() => setActiveTooltip(index)}
                          onMouseLeave={() => setActiveTooltip(null)}
                          className="text-gray-400 hover:text-gray-600"
                        >
                          <HelpCircle className="w-4 h-4" />
                        </button>
                        {activeTooltip === index && (
                          <div className="absolute left-6 top-0 z-50 w-64 p-3 bg-gray-900 text-white text-sm rounded-lg shadow-xl">
                            {row.tooltip}
                            <div className="absolute left-0 top-2 -translate-x-1 w-2 h-2 bg-gray-900 rotate-45" />
                          </div>
                        )}
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-5 text-center">
                    <TableCell
                      value={row.googleAdX.value}
                      positive={row.googleAdX.positive}
                    />
                  </td>
                  <td className="px-6 py-5 text-center">
                    <TableCell
                      value={row.magnite.value}
                      positive={row.magnite.positive}
                    />
                  </td>
                  <td className="px-6 py-5 text-center bg-emerald-50 group-hover:bg-emerald-100 transition-colors">
                    <TableCell
                      value={row.ours.value}
                      positive={row.ours.positive}
                      highlight
                    />
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </motion.div>

        {/* Mobile Cards */}
        <div className="md:hidden space-y-4">
          {comparisonData.map((row, index) => (
            <MobileComparisonCard
              key={row.feature}
              data={row}
              index={index}
              isInView={isInView}
            />
          ))}
        </div>

        {/* Bottom CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.8 }}
          className="mt-12 text-center"
        >
          <p className="text-gray-600 mb-4">
            Ready to see the difference for yourself?
          </p>
          <a
            href="#demo"
            className="inline-flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors"
          >
            Try Our Demo
          </a>
        </motion.div>
      </div>
    </section>
  );
}

function TableCell({
  value,
  positive,
  highlight = false,
}: {
  value: string;
  positive: boolean;
  highlight?: boolean;
}) {
  return (
    <div
      className={`inline-flex items-center gap-2 ${
        highlight ? "font-semibold" : ""
      }`}
    >
      {positive ? (
        <Check
          className={`w-5 h-5 ${
            highlight ? "text-emerald-600" : "text-emerald-500"
          }`}
        />
      ) : (
        <X className="w-5 h-5 text-red-400" />
      )}
      <span
        className={
          highlight
            ? "text-emerald-700"
            : positive
            ? "text-gray-900"
            : "text-gray-600"
        }
      >
        {value}
      </span>
    </div>
  );
}

function MobileComparisonCard({
  data,
  index,
  isInView,
}: {
  data: ComparisonRow;
  index: number;
  isInView: boolean;
}) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.4, delay: 0.2 + index * 0.1 }}
      className="bg-white rounded-xl border border-gray-200 shadow-lg overflow-hidden"
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-4 py-4 flex items-center justify-between bg-gray-50"
      >
        <span className="font-semibold text-gray-900">{data.feature}</span>
        <ChevronDown
          className={`w-5 h-5 text-gray-500 transition-transform ${
            isOpen ? "rotate-180" : ""
          }`}
        />
      </button>

      {isOpen && (
        <div className="p-4 space-y-3">
          <div className="flex justify-between items-center py-2 border-b border-gray-100">
            <span className="text-sm text-gray-500">Google AdX</span>
            <TableCell
              value={data.googleAdX.value}
              positive={data.googleAdX.positive}
            />
          </div>
          <div className="flex justify-between items-center py-2 border-b border-gray-100">
            <span className="text-sm text-gray-500">Magnite</span>
            <TableCell
              value={data.magnite.value}
              positive={data.magnite.positive}
            />
          </div>
          <div className="flex justify-between items-center py-2 px-3 bg-emerald-50 rounded-lg">
            <span className="text-sm font-medium text-emerald-700">
              Our Web3
            </span>
            <TableCell
              value={data.ours.value}
              positive={data.ours.positive}
              highlight
            />
          </div>
          <p className="text-xs text-gray-500 pt-2">{data.tooltip}</p>
        </div>
      )}
    </motion.div>
  );
}
